// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Nakildias <nakildiaspro@gmail.com>
//
// Writes ~/.config/alsa/waveline.conf so ALSA apps (Audacity, Wine, …) see
// Waveline endpoints by name. Regenerated whenever input devices or published
// channel mics change. Does not create PipeWire nodes.
//
// Recording list is intentionally small:
//   Waveline Wave:3 / Input #1 …  — processed input devices (never "mic")
//   published channel mics
//   Stream / Monitor mix taps
// Channel sinks stay PipeWire/Pulse only so Audacity is not littered with
// Game/Music/… entries that used to all capture the same mic.

#include "alsaaliases.h"

#include <QDir>
#include <QFile>
#include <QSaveFile>
#include <QStandardPaths>
#include <QTextStream>

#include "engine/masterbus.h"

namespace {

QString alsaConfigDir() {
    return QDir(QStandardPaths::writableLocation(QStandardPaths::ConfigLocation))
        .filePath(QStringLiteral("alsa"));
}

QString alsaConfPath() {
    return QDir(alsaConfigDir()).filePath(QStringLiteral("waveline.conf"));
}

QString alsaAsoundrcPath() {
    return QDir(alsaConfigDir()).filePath(QStringLiteral("asoundrc"));
}

QString pcmName(const QString &suffix) {
    QString s;
    s.reserve(suffix.size());
    for (QChar c : suffix) {
        if (c.isLetterOrNumber())
            s += c;
        else
            s += QLatin1Char('_');
    }
    while (s.contains(QLatin1String("__"))) s.replace(QLatin1String("__"), QLatin1String("_"));
    if (s.endsWith(QLatin1Char('_'))) s.chop(1);
    return QStringLiteral("waveline_") + s;
}

QString escapeAlsa(const QString &s) {
    QString out;
    out.reserve(s.size());
    for (QChar c : s) {
        if (c == QLatin1Char('\\') || c == QLatin1Char('"'))
            out += QLatin1Char('\\');
        out += c;
    }
    return out;
}

void writePcm(QTextStream &out, const QString &name, const QString &playbackNode,
              const QString &captureNode, const QString &description) {
    out << "pcm." << name << " {\n"
        << "\ttype pipewire\n"
        << "\tplayback_node \"" << escapeAlsa(playbackNode) << "\"\n"
        << "\tcapture_node \"" << escapeAlsa(captureNode) << "\"\n"
        << "\thint {\n"
        << "\t\tshow on\n"
        << "\t\tdescription \"" << escapeAlsa(description) << "\"\n"
        << "\t}\n"
        << "}\n\n";
}

void ensureAsoundrcInclude(const QString &confPath) {
    const QString asoundrc = alsaAsoundrcPath();
    QDir().mkpath(alsaConfigDir());
    const QString includeLine = QLatin1Char('<') + confPath + QLatin1Char('>');
    const QString marker = QStringLiteral("# Waveline ALSA device aliases");

    QFile f(asoundrc);
    if (f.exists() && f.open(QIODevice::ReadOnly | QIODevice::Text)) {
        const QString body = QString::fromUtf8(f.readAll());
        f.close();
        if (body.contains(confPath)) return;
        QSaveFile out(asoundrc);
        if (!out.open(QIODevice::WriteOnly | QIODevice::Text)) return;
        QTextStream ts(&out);
        ts << marker << '\n' << includeLine << "\n\n" << body;
        out.commit();
        return;
    }

    QSaveFile out(asoundrc);
    if (!out.open(QIODevice::WriteOnly | QIODevice::Text)) return;
    QTextStream ts(&out);
    ts << marker << '\n' << includeLine << '\n';
    out.commit();
}

}  // namespace

namespace waveline {

bool syncAlsaAliases(const MixerGraph &graph, const std::string &brand,
                     QString *error) {
    const QString confPath = alsaConfPath();
    QDir().mkpath(alsaConfigDir());
    ensureAsoundrcInclude(confPath);

    QSaveFile file(confPath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        if (error)
            *error = QStringLiteral("cannot write %1 (%2)")
                         .arg(confPath, file.errorString());
        return false;
    }

    QTextStream out(&file);
    const QString brandQ = QString::fromStdString(brand.empty() ? "Waveline" : brand);

    out << "# SPDX-License-Identifier: GPL-2.0-or-later\n"
        << "# Auto-generated by wavelined — do not edit.\n"
        << "# Regenerated when input devices or published channel mics change.\n"
        << "# ALSA namehints only; PipeWire / pavucontrol are unchanged.\n\n";

    // Processed input devices in strip order. PCM id is waveline_input_N (never "mic").
    out << "# ---- processed input devices ----\n";
    int inputIndex = 0;
    for (const MasterBusRuntime &bus : graph.masterBuses()) {
        if (!bus.chain.sourceReady) continue;
        ++inputIndex;
        const QString node = QString::fromStdString(masterSourceNode(bus.id));
        const QString pcm = pcmName(QStringLiteral("input_%1").arg(inputIndex));
        const QString stripName =
            bus.name.empty() ? QStringLiteral("Input #%1").arg(inputIndex)
                             : QString::fromStdString(bus.name);
        const QString desc = brandQ + QLatin1Char(' ') + stripName;
        writePcm(out, pcm, QStringLiteral("-1"), node, desc);
    }

    // Channels that publish their own microphone as a recording device.
    out << "# ---- published channel microphones ----\n";
    for (const Channel &c : graph.channels()) {
        if (!c.micSource) continue;
        const QString id = QString::fromStdString(c.id);
        const QString node = QStringLiteral("waveline-") + id + QStringLiteral("-mic");
        const QString chName =
            c.name.empty() ? id : QString::fromStdString(c.name);
        const QString desc =
            brandQ + QLatin1Char(' ') + chName + QStringLiteral(" Microphone");
        writePcm(out, pcmName(id + QStringLiteral("_mic")), QStringLiteral("-1"),
                 node, desc);
    }

    // Mix taps.
    out << "# ---- mix monitors ----\n";
    writePcm(out, QStringLiteral("waveline_stream"),
             QStringLiteral("waveline-stream-mix"),
             QStringLiteral("waveline-stream-mix.monitor"),
             brandQ + QStringLiteral(" Stream Mix"));
    writePcm(out, QStringLiteral("waveline_monitor"),
             QStringLiteral("waveline-monitor-mix"),
             QStringLiteral("waveline-monitor-mix.monitor"),
             brandQ + QStringLiteral(" Monitor Mix"));

    if (!file.commit()) {
        if (error)
            *error = QStringLiteral("failed to commit %1").arg(confPath);
        return false;
    }
    return true;
}

}  // namespace waveline
