// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Nakildias <nakildiaspro@gmail.com>

#include "wpheadroom.h"

#include <QDir>
#include <QFile>
#include <QProcess>
#include <QSaveFile>
#include <QStandardPaths>

namespace waveline {
namespace {

QString dropInDir() {
    return QDir(QStandardPaths::writableLocation(QStandardPaths::ConfigLocation))
        .filePath(QStringLiteral("wireplumber/wireplumber.conf.d"));
}

QString dropInPath() {
    return QDir(dropInDir())
        .filePath(QStringLiteral("99-waveline-output-headroom.conf"));
}

QString ruleFor(int frames) {
    return QStringLiteral(
               "# SPDX-License-Identifier: GPL-2.0-or-later\n"
               "# Generated by wavelined. Change the value in the mixer\n"
               "# (Non-USB output headroom); edits here are overwritten.\n"
               "#\n"
               "# Slack in the ALSA buffer of output devices that are not the\n"
               "# graph clock. Without it a follower underruns the moment the\n"
               "# machine is busy -- audible as crackle on every output except\n"
               "# the one driving the graph.\n"
               "#\n"
               "# The alsa_output.pci- prefix excludes USB by construction,\n"
               "# which is required: a rule touching the Wave:3's output node\n"
               "# silences its ADC for the session. See\n"
               "# 50-waveline-driver-policy.conf.\n"
               "monitor.alsa.rules = [\n"
               "  {\n"
               "    matches = [\n"
               "      {\n"
               "        node.name = \"~alsa_output.pci-.*\"\n"
               "      }\n"
               "    ]\n"
               "    actions = {\n"
               "      update-props = {\n"
               "        api.alsa.headroom = %1\n"
               "      }\n"
               "    }\n"
               "  }\n"
               "]\n")
        .arg(frames);
}

}  // namespace

bool writeOutputHeadroom(int frames, QString *error) {
    const QString path = dropInPath();

    if (frames <= 0) {
        // Absent, not zero. A rule writing 0 looks identical to PipeWire's
        // default but keeps a Waveline file on a machine that has opted out,
        // and the next person to debug this deserves an empty directory.
        if (!QFile::exists(path)) return true;
        if (QFile::remove(path)) return true;
        if (error) *error = QStringLiteral("could not remove %1").arg(path);
        return false;
    }

    const QString want = ruleFor(frames);
    QFile existing(path);
    if (existing.open(QIODevice::ReadOnly)) {
        const QString have = QString::fromUtf8(existing.readAll());
        existing.close();
        if (have == want) return true;
    }

    if (!QDir().mkpath(dropInDir())) {
        if (error) *error = QStringLiteral("could not create %1").arg(dropInDir());
        return false;
    }
    // QSaveFile so a half-written rule never reaches WirePlumber, which is
    // watching this directory and will read whatever is there.
    QSaveFile out(path);
    if (!out.open(QIODevice::WriteOnly | QIODevice::Text)) {
        // The usual cause is the systemd unit: ProtectHome=read-only without
        // ~/.config/wireplumber in ReadWritePaths fails the write and nothing
        // else, so say which file could not be written rather than "failed".
        if (error)
            *error = QStringLiteral("could not write %1: %2")
                         .arg(path, out.errorString());
        return false;
    }
    out.write(want.toUtf8());
    if (!out.commit()) {
        if (error)
            *error = QStringLiteral("could not save %1: %2")
                         .arg(path, out.errorString());
        return false;
    }
    return true;
}

bool restartWirePlumber(QString *error) {
    // Detached on purpose. The daemon's own PipeWire connections go down with
    // WirePlumber and come back a moment later, and waiting for systemctl here
    // would block the thread that has to service them.
    const bool ok = QProcess::startDetached(
        QStringLiteral("systemctl"),
        {QStringLiteral("--user"), QStringLiteral("restart"),
         QStringLiteral("wireplumber")});
    if (!ok && error)
        *error = QStringLiteral("could not run systemctl --user restart wireplumber");
    return ok;
}

}  // namespace waveline
